## Q1

In [1]:
import numpy as np

np.random.seed(1)
rnd_arr = np.random.randint(1,51,size=(5,4))

In [2]:
# 1
print(rnd_arr, '\n')

#2
anti_diag = [rnd_arr[i, -1-i] for i in range(min(rnd_arr.shape))]
print(np.uint64(anti_diag), '\n')

max_val = [max(rnd_arr[i,:]) for i in range(rnd_arr.shape[1])]
print(np.uint64(max_val))

[[38 44 13  9]
 [10 12  6 16]
 [ 1 17  2 13]
 [ 8 46  7 26]
 [21 38 19 21]] 

[ 9  6 17  8] 

[44 16 17 46]


In [3]:
# 3
mean = np.int64(np.mean(rnd_arr))
print(mean, '\n')

np.random.seed(1)
mean_arr = np.random.randint(1,mean+1,size=(5,4))
print(mean_arr)

18 

[[ 6 12 13  9]
 [10 12  6 16]
 [ 1 17  2 13]
 [ 8 14  7  6]
 [12 11 15  5]]


In [4]:
# 4
def numpy_boundary_traversal(matrix):
    rows, cols = matrix.shape
    boundary_elements = []

    boundary_elements.extend(matrix[0, :])
    boundary_elements.extend(matrix[1:rows-1, cols-1])
    boundary_elements.extend(matrix[rows-1, ::-1])
    boundary_elements.extend(matrix[rows-2:0:-1, 0])

    return boundary_elements

In [5]:
print(numpy_boundary_traversal((mean_arr)))

[np.int64(6), np.int64(12), np.int64(13), np.int64(9), np.int64(16), np.int64(13), np.int64(6), np.int64(5), np.int64(15), np.int64(11), np.int64(12), np.int64(8), np.int64(1), np.int64(10)]


## Q2

In [6]:
flt_rnd_arr = np.random.uniform(1,11, size=(20,))

In [7]:
# 1
print(flt_rnd_arr, '\n')

print(np.round(flt_rnd_arr,2))

[ 5.17304802  6.58689828  2.40386939  2.98101489  9.00744569 10.68261576
  4.13424178  7.92322616  9.76389152  9.94606664  1.85044211  1.39054783
  2.6983042   9.78142503  1.98346834  5.21107625 10.5788953   6.33165285
  7.91877114  4.15515631] 

[ 5.17  6.59  2.4   2.98  9.01 10.68  4.13  7.92  9.76  9.95  1.85  1.39
  2.7   9.78  1.98  5.21 10.58  6.33  7.92  4.16]


In [8]:
# 2

max_num = np.max(flt_rnd_arr)
min_num = np.min(flt_rnd_arr)
median_num = np.median(flt_rnd_arr)

print("Max: ",max_num," Min: ",min_num," Median: ",median_num)

Max:  10.682615757193975  Min:  1.3905478323288236  Median:  5.771364549890347


In [9]:
# 3
list_np = list(map(float,flt_rnd_arr))

modified_arr = [i**2 if i<5 else i for i in list_np]
modified_arr = np.array(modified_arr)
print(modified_arr)

[ 5.17304802  6.58689828  5.77858802  8.88644978  9.00744569 10.68261576
 17.09195511  7.92322616  9.76389152  9.94606664  3.42413602  1.93362327
  7.28084553  9.78142503  3.93414665  5.21107625 10.5788953   6.33165285
  7.91877114 17.26532396]


In [10]:
# 4

def numpy_alternate_sort(array):
  sorted_arr = np.sort(array)

  alt_sorted = []
  left = 0
  right = len(sorted_arr) - 1

  while left <= right:
    alt_sorted.append(sorted_arr[left])
    left += 1
    if left <= right:
        alt_sorted.append(sorted_arr[right])
        right -= 1

  return list(map(float,alt_sorted))

In [11]:
print(numpy_alternate_sort(modified_arr))

[1.9336232739943902, 17.265323961036668, 3.4241360161463046, 17.091955108664536, 3.9341466491595587, 10.682615757193975, 5.17304802367127, 10.57889530150502, 5.211076250050522, 9.946066635038473, 5.77858802471887, 9.78142503429413, 6.331652849730171, 9.763891522960384, 6.586898284457517, 9.007445686755366, 7.28084553223913, 8.88644977946221, 7.9187711395047335, 7.923226156693141]


## Q3

In [12]:
# 1
import pandas as pd

np.random.seed(5)
rows = [['Srinivasa', 'Maths', np.random.randint(50,101), np.nan],
        ['Tesla', 'Physics', np.random.randint(50,101), np.nan],
        ['Isaac', 'Physics', np.random.randint(50,101), np.nan],
        ['Erwin', 'Quantum Physics', np.random.randint(50,101), np.nan],
        ['Marie', 'Chemistry', np.random.randint(50,101), np.nan],
        ['Sidhant', 'Electronics', np.random.randint(50,101), np.nan],
        ['Holmes', 'Philosopy', np.random.randint(50,101), np.nan],
        ['Sauain', 'AI/ML', np.random.randint(50,101), np.nan],
        ['Viraj', 'Verilog', np.random.randint(50,101), np.nan],
        ['Soumya', 'Fluid Dynamics', np.random.randint(50,101), np.nan],]

In [13]:
df = pd.DataFrame(data=rows ,columns=['Name', 'Subject', 'Score', 'Grade'])
print(df)

        Name          Subject  Score  Grade
0  Srinivasa            Maths     85    NaN
1      Tesla          Physics     64    NaN
2      Isaac          Physics     97    NaN
3      Erwin  Quantum Physics     88    NaN
4      Marie        Chemistry     66    NaN
5    Sidhant      Electronics     59    NaN
6     Holmes        Philosopy     58    NaN
7     Sauain            AI/ML     86    NaN
8      Viraj          Verilog     89    NaN
9     Soumya   Fluid Dynamics     77    NaN


In [14]:
df['Grade'] = df['Score'].apply(lambda x: 'A' if x>90 else 'B' if x>80 else 'C' if x>70 else 'D' if x>60 else 'F')
print(df)

        Name          Subject  Score Grade
0  Srinivasa            Maths     85     B
1      Tesla          Physics     64     D
2      Isaac          Physics     97     A
3      Erwin  Quantum Physics     88     B
4      Marie        Chemistry     66     D
5    Sidhant      Electronics     59     F
6     Holmes        Philosopy     58     F
7     Sauain            AI/ML     86     B
8      Viraj          Verilog     89     B
9     Soumya   Fluid Dynamics     77     C


In [15]:
# 2
data = df.copy()

data_sorted = data.sort_values(by='Score', ascending=False)
print(data_sorted)

        Name          Subject  Score Grade
2      Isaac          Physics     97     A
8      Viraj          Verilog     89     B
3      Erwin  Quantum Physics     88     B
7     Sauain            AI/ML     86     B
0  Srinivasa            Maths     85     B
9     Soumya   Fluid Dynamics     77     C
4      Marie        Chemistry     66     D
1      Tesla          Physics     64     D
5    Sidhant      Electronics     59     F
6     Holmes        Philosopy     58     F


In [16]:
# 3
avg_score_per_subject = df.groupby('Subject')['Score'].mean()
print("\nAverage Score per Subject:\n", avg_score_per_subject)


Average Score per Subject:
 Subject
AI/ML              86.0
Chemistry          66.0
Electronics        59.0
Fluid Dynamics     77.0
Maths              85.0
Philosopy          58.0
Physics            80.5
Quantum Physics    88.0
Verilog            89.0
Name: Score, dtype: float64


In [17]:
# 4

def pandas_filter_pass(dataframe):
    return dataframe[dataframe['Grade'].isin(['A', 'B'])]

print("\nFiltered (Grade A or B):\n", pandas_filter_pass(df))


Filtered (Grade A or B):
         Name          Subject  Score Grade
0  Srinivasa            Maths     85     B
2      Isaac          Physics     97     A
3      Erwin  Quantum Physics     88     B
7     Sauain            AI/ML     86     B
8      Viraj          Verilog     89     B


## Q4

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [19]:
# Step 1:
positive_reviews = ["I loved the movie!", "Amazing experience", "Fantastic plot", "Great direction",
                    "Loved the acting", "Brilliant!", "It was a masterpiece", "Best film ever",
                    "Would watch again", "Incredible visuals"] * 5  # 50 reviews

negative_reviews = ["I hated the movie", "Terrible experience", "Boring plot", "Poor direction",
                    "Bad acting", "Awful!", "It was a disaster", "Worst film ever",
                    "Never watching again", "Horrible visuals"] * 5  # 50 reviews

reviews = positive_reviews + negative_reviews
sentiments = ['positive'] * 50 + ['negative'] * 50

df = pd.DataFrame({'Review': reviews, 'Sentiment': sentiments})

In [20]:
# Step 2:
vectorizer = CountVectorizer(max_features=500, stop_words='english')
X = vectorizer.fit_transform(df['Review'])
y = df['Sentiment']

In [21]:
# Step 3:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [22]:
# Step 4:
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [23]:
# Step 5: Evaluate
y_pred = model.predict(X_test)
print("Accuracy on test set:", accuracy_score(y_test, y_pred))

Accuracy on test set: 1.0


In [24]:
# Step 6: Prediction function
def predict_review_sentiment(model, vectorizer, review):
    review_vector = vectorizer.transform([review])
    return model.predict(review_vector)[0]

In [25]:
example = "The movie was breathtaking and beautiful"
print("Predicted Sentiment:", predict_review_sentiment(model, vectorizer, example))

Predicted Sentiment: negative


## Q5

In [26]:
import random
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score, f1_score

In [27]:
# 1.
positive_samples = ["This product is great!", "Loved it", "Excellent service", "Very satisfied", "Highly recommend"] * 10
negative_samples = ["Terrible product", "Not happy", "Worst experience", "Do not buy this", "Disappointed"] * 10
texts = positive_samples + negative_samples
labels = [1]*50 + [0]*50  # 1: good, 0: bad

In [28]:
# Shuffle the dataset
combined = list(zip(texts, labels))
random.shuffle(combined)
texts, labels = zip(*combined)

In [29]:
# 2.
vectorizer = TfidfVectorizer(max_features=300, stop_words='english', lowercase=True)
X = vectorizer.fit_transform(texts)

In [30]:
# 3.
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.25, random_state=42)


In [31]:
# 4.
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [32]:
# 5.
y_pred = model.predict(X_test)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

In [33]:
print(f"Precision: {precision:.2f}")
print(f"Recall:    {recall:.2f}")
print(f"F1-score:  {f1:.2f}")

Precision: 1.00
Recall:    1.00
F1-score:  1.00


In [34]:
# 6.
def text_preprocess_vectorize(texts, vectorizer):
    return vectorizer.transform(texts)

In [35]:
new_samples = ["I hated this!", "Amazing experience"]
X_new = text_preprocess_vectorize(new_samples, vectorizer)
predictions = model.predict(X_new)
print(predictions)  # Output: [0 1]

[0 0]
